version: "3"

tasks:
  remove:
    desc: Remove the gh extension
    ignore_error: true
    cmds:
      - gh extension remove wt

  install:
    desc: Install the gh extension locally
    deps: [remove, build]
    cmds:
      - gh extension install . --force

  run:
    desc: Run the installed extension
    cmds:
      - gh wt{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  dev:
    desc: Build and run the extension for development
    deps: [build]
    cmds:
      - ./gh-wt{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  version:
    desc: Get current version from git tags
    cmds:
      - git describe --tags --dirty --always

  build:
    desc: Build the extension binary
    vars:
      VERSION:
        sh: git describe --tags --dirty --always 2>/dev/null | sed 's/^v//' || echo "dev"
    cmds:
      - go build -ldflags "-X=github.com/ffalor/gh-wt/cmd.Version={{.VERSION}}" -o gh-wt

  clean:
    desc: Remove built binary
    cmds:
      - rm -f gh-wt
