# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    cmds:
      - go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run gh-wt

  debug:
    cmds:
      - DEBUG=true go run . --debug {{.CLI_ARGS}}
    interactive: true
    desc: Run in debug mode

  fmt:
    desc: Run gofumpt on changed files
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix --new-from-merge-base=main
    env:
      GOEXPERIMENT: null

  lint:
    desc: Run linters on changed files
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --new-from-merge-base=main
    env:
      GOEXPERIMENT: null

  lint-fix:
    desc: Run linters and fix issues on changed files
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix --new-from-merge-base=main
    env:
      GOEXPERIMENT: null

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Remove built binary and dist
    cmds:
      - rm -f gh-wt
      - rm -rf dist

  install:
    desc: Install the gh extension locally
    cmds:
      - gh extension install . --force

  remove:
    desc: Remove the gh extension
    ignore_error: true
    cmds:
      - gh extension remove wt
